from dotenv import dotenv_values, find_dotenv

CONFIG = dotenv_values(find_dotenv())


# CURRENT SEASON AND EXPANSION
WOW_CURRENT_SEASON = CONFIG["WOW_CURRENT_SEASON"]
WOW_CURRENT_EXPANSION = CONFIG["WOW_CURRENT_EXPANSION"]

# DB LOGIN URL
DB_URL = f'postgres://{CONFIG["DB_USER"]}:{CONFIG["DB_PASSWORD"]}@{CONFIG["DB_HOST"]}/{CONFIG["DB_NAME"]}'

# BOT SETTINGS
BOT_TOKEN = CONFIG["TOKEN"]
BOT_CHANNEL_NAME = CONFIG["DISCORD_CHANNEL_NAME"]

# API SETTINGS RAIDER IO
WOW_API_URL = CONFIG["WOW_API_URL"]
ALTERNATIVE_RUN_FIELDS = CONFIG["ALTERNATIVE_RUN_FIELDS"]
BEST_RUN_FIELDS = CONFIG["BEST_RUN_FIELDS"]

# WOW
TOKEN_BASE_URL = CONFIG["TOKEN_BASE_URL"]
TOKEN_PICTURE_URL = CONFIG["TOKEN_PICTURE_URL"]

# DISCORD CORRECT CHANNEL NAME
DISCORD_CHANNEL_NAME = CONFIG["DISCORD_CHANNEL_NAME"]
