from dotenv import dotenv_values, find_dotenv

CONFIG = dotenv_values(find_dotenv())


# CURRENT SEASON AND EXPANSION
WOW_CURRENT_SEASON = CONFIG["WOW_CURRENT_SEASON"]
WOW_CURRENT_EXPANSION = CONFIG["WOW_CURRENT_EXPANSION"]

# DB LOGIN URL
DB_URL = f'postgres://{CONFIG["DB_USER"]}:{CONFIG["DB_PASSWORD"]}@{CONFIG["DB_HOST"]}/{CONFIG["DB_NAME"]}'

# BOT SETTINGS
BOT_TOKEN = CONFIG["TOKEN"]
BOT_CHANNEL_NAME = CONFIG["DISCORD_CHANNEL_NAME"]

# API SETTINGS RAIDER IO
WOW_API_URL = CONFIG["WOW_API_URL"]
ALTERNATIVE_RUN_FIELDS = CONFIG["ALTERNATIVE_RUN_FIELDS"]
BEST_RUN_FIELDS = CONFIG["BEST_RUN_FIELDS"]
CURRENT_SEASON_SCORE = CONFIG["CURRENT_SEASON_SCORE"]
RAID_PROGRESSION = CONFIG["RAID_PROGRESSION"]
GEAR = CONFIG["GEAR"]
MYTHIC_PLUS_RECENT_RUNS = CONFIG["MYTHIC_PLUS_RECENT_RUNS"]

# WOW
TOKEN_BASE_URL = CONFIG["TOKEN_BASE_URL"]
TOKEN_PICTURE_URL = CONFIG["TOKEN_PICTURE_URL"]
FOOTER_EMBED_PICTURE_URL = CONFIG["FOOTER_EMBED_PICTURE_URL"]


# CHARACTER ADDITION LINKS
WOW_BASE_URL = CONFIG["WOW_BASE_URL"]
RAIDBOTS_BASE_URL = CONFIG["RAIDBOTS_BASE_URL"]
WOW_LOG_BASE_URL = CONFIG["WOW_LOG_BASE_URL"]

#PICTURES
GEAR_PROGRESSION = CONFIG["GEAR_PROGRESSION"]

# GUIDES LINK
WOWHEAD_SEASON_GEAR_GUIDE = CONFIG["WOWHEAD_SEASON_GEAR_GUIDE"]
